### ISSUE TITLE
Extension to 87 <= Z <= 103

### ISSUE THREAD

**Issue by marcelmbn** [grimme-lab/MindlessGen#27]
## Current state

Limitation to elements with Z<=86 as `xtb` and most standard ORCA setups are not provided for heavier atoms.

## How to enhance?

Special case for Z > 86
- Generate analog molecule with heavy atoms replaced by the lower period analog after the "generate & refinement" step (Fr -> Cs, U -> Nd, ...)
- In `post-processing`: Optimize structure with replaced atoms and by using ORCA with a matching basis set
- raise warning if no post-processing shall be conducted (structure would not be relaxed after element replacement)

**Comment by jonathan-schoeps** [comment]
## Idea on how to implement

- Like the ufh problem with lanthanides, replace the actinides with the corresponding lanthanides before the xtb run, then xtb calculates and finally reassigns the correct actinide.
- Create a new class with warnings where each case of "special" treatment has a corresponding warning and print it to the console when this case is met.
