### ISSUE TITLE
Use covalent radii of the atoms inside the check_distance function

### ISSUE THREAD

**Issue by jonathan-schoeps** [grimme-lab/MindlessGen#42]
## Current status

`check_distance` in `generate_molecule.py` checks all inter-atomic distances based on a global threshold from `ConfigClass`.

- Atoms with very small radii like hydrogen are not put close together, while super large atoms like Pb might be placed too close to each other.

## How to improve

Take the covalent radii from `refinement.py` and use it to calculate the distance threshold between the atom pairs.

**Comment by marcelmbn** [comment]
## Current status 
`check_distance` in `generate_molecule.py` checks all inter-atomic distances based on a global threshold taken from `ConfigClass`.

- Atoms with very small radii like hydrogen are not put close together, while super large atoms like Pb might be placed too close to each other.

## How to improve
Take the covalent radii from `refinement.py` and use it to calculate the distance threshold between the atom pairs.
