### ISSUE TITLE
Development feature: Use GP3-xTB each time a new compound is generated

### ISSUE THREAD

**Issue by marcelmbn** [grimme-lab/MindlessGen#43]
- implement a GP3-xTB `QMMethod` class
- conduct a GP3-xTB single-point calculation everytime a GFN_n_-xTB refinement has been successful
- check for properties
   - HOMO-LUMO gap < 1.5 eV
   - less than 500 SCF cycles

**If calculation doesn't converge/doesn't meet requirements, dump structure to file and label accordingly!**

**Comment by marcelmbn** [comment]
Would be closed with https://github.com/grimme-lab/MindlessGen/pull/49 and an additional code block from https://github.com/marcelmbn/MindlessGen/blob/dev/gp3_testing/src/mindlessgen/generator/main.py (currently, the following lines: 

https://github.com/marcelmbn/MindlessGen/blob/4107338cfa719104954d3d07a65a547f6227dcfd/src/mindlessgen/generator/main.py#L222-L250

FYI: @jonathan-schoeps

**Comment by jonathan-schoeps** [comment]
This implementation should work now.
