### ISSUE TITLE
Update the ReadMe.MD

### ISSUE THREAD

**Issue by jonathan-schoeps** [grimme-lab/MindlessGen#48]
# Update
There is insufficient documentation on how to use the "fixed element composition".

**Comment by marcelmbn** [comment]
This is probably also relevant for the ternary oxides, so it might make sense that you enhance the `README.md` for this (currently not well documented) case.

**Comment by marcelmbn** [comment]
In addition to this, the following part of `mindlessgen.toml` is a bit inconsistent (just noticed after merging https://github.com/grimme-lab/MindlessGen/pull/51).

```
# > Scaling factor for the employed van der Waals radii. Options: <float>
scale_vdw_radii = 1.2
# > Scaling factor for the minimal bondlength based on the sum of the van der Waals radii. Options: <float>
scale_minimal_bondlength = 0.75
```

Which scaling factors are scaled in the end? This should be more clear and consistent, @jonathan-schoeps.
