### ISSUE TITLE
Wildcard in element_composition probably not working correctly

### ISSUE THREAD

**Issue by gasevic** [grimme-lab/MindlessGen#93]
The element_composition setting in the mindlessgen.toml file allows for wildcard integer values e.g. with 

`element_composition = "Ga:1-*"`

but all structures that come out only include the minimum count instead of random integer numbers.

**Comment by marcelmbn** [comment]
Due to the principle of the code, this is basically a copy of https://github.com/grimme-lab/MindlessGen/issues/76.
Will close this issue with the above one as soon as it's resolved.
